kind: Deployment
apiVersion: apps/v1
metadata:
  name: mrdevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
        - name: mrdevops
          image: kartik2311/pipe   # Include a specific version tag
          imagePullPolicy: Always
          ports:
            - containerPort: 80
